version: '3.8'

services:

 avito_trainee_backend:
  image: avito:latest
  build:
   context: ./Application
   dockerfile: Dockerfile
  environment:
   PG_DB_USERNAME: ${PG_DB_USERNAME}
   PG_DB_PASSWORD: ${PG_DB_PASSWORD}
   PG_DB_IP_ADDRESS: ${PG_DB_IP_ADDRESS}
   PG_DB_PORT: ${PG_DB_PORT}
  depends_on:
   - database
  ports:
   - "127.0.0.1:8000:8080"
  networks:
   - postgres
   
 database:
  image: database:latest
  build:
   context: ./Database
   dockerfile: Dockerfile
  environment:
   POSTGRES_DB: ${PG_DB_NAME}
   POSTGRES_USER: ${PG_DB_USERNAME}
   POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
   PGDATA: "/var/lib/postgresql/data/pgdata"
  ports:
   - "5431:5432"
  networks:
   - postgres
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres -d segments_service"]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 20s
   
networks:
 postgres:
  driver: bridge
